Fix strip determinism on Windows

diff --git a/BinaryBuilderToolchains.jl/test/testsuite/CToolchain/05_lock_microarchitecture/Makefile b/BinaryBuilderToolchains.jl/test/testsuite/CToolchain/05_lock_microarchitecture/Makefile
--- a/BinaryBuilderToolchains.jl/test/testsuite/CToolchain/05_lock_microarchitecture/Makefile
+++ b/BinaryBuilderToolchains.jl/test/testsuite/CToolchain/05_lock_microarchitecture/Makefile
@@ -9,15 +9,23 @@ $(PROJECT_DIR)/build:
 clean:
 	rm -rf $(PROJECT_DIR)/build
 
+$(PROJECT_DIR)/build/lock_march.o: lock_march.c | $(PROJECT_DIR)/build
+	@BB_WRAPPERS_VERBOSE=1 $(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) $< >$@.log 2>$@.log
+
+$(PROJECT_DIR)/build/lock_march_fail.o.log: lock_march.c | $(PROJECT_DIR)/build
+	-@BB_WRAPPERS_VERBOSE=1 $(CC) -c -o $(PROJECT_DIR)/build/lock_march_fail.o $(CPPFLAGS) $(CFLAGS) -march=native $< >$@ 2>$@
+
+compile: $(PROJECT_DIR)/build/lock_march.o $(PROJECT_DIR)/build/lock_march_fail.o.log
+
 run: check
-check: lock_march.c | $(PROJECT_DIR)/build
-	@# First, try to compile with `-march=native`, which will fail:
-	@if $(CC) -c -o $(PROJECT_DIR)/build/lock_march_fail.o $(CPPFLAGS) $(CFLAGS) -march=native $< 2>/dev/null ; then \
+check: compile
+	@# First, ensure that compiling with `-march` failed:
+	@if [ -f $(PROJECT_DIR)/build/lock_march_fail.o ]; then \
 		echo 'Compilation with `-march=native` did not fail!' >&2; \
+		cat $(PROJECT_DIR)/build/lock_march_fail.o.log >&2; \
 		false; \
 	fi
-	@# Next, compile normally, this time with `BB_WRAPPERS_VERBOSE` enabled to check that `-march` is added:
-	@BB_WRAPPERS_VERBOSE=1 $(CC) -c -o $(PROJECT_DIR)/build/lock_march.o $(CPPFLAGS) $(CFLAGS) $< >$(PROJECT_DIR)/build/lock_march.o.log 2>$(PROJECT_DIR)/build/lock_march.o.log
+	@# Next, ensure that when run with `BB_WRAPPERS_VERBOSE`, `-march` was automatically added:
 	@if ! grep -q "\-march" $(PROJECT_DIR)/build/lock_march.o.log; then \
 		echo 'No `-march` flag found in compiler output:' >&2; \
 		cat $(PROJECT_DIR)/build/lock_march.o.log >&2; \
