Improve `save_env_hook`
Finally... FINALLY... I have fixed the issue that the erroring command
appears in the log three times.  `bash` is a harsh mistress.

diff --git a/share/bash_scripts/save_env_hook b/share/bash_scripts/save_env_hook
--- a/share/bash_scripts/save_env_hook
+++ b/share/bash_scripts/save_env_hook
@@ -1,9 +1,17 @@
 #!/bin/bash
 
 # Save bash history (and optionally echo it out as it happens)
-save_history() {
+# This is defined here, but the trap is only enabled in the `build_script.sh` that is generated by `BuildConfig`.
+# This avoids annoyances like this trap being enabled during debug shells, etc....
+function save_history() {
+	# When a command fails, we enter the `ERR` trap, which starts to run statements, but we want to
+	# ignore those, so we explicitly catch it here, and then disable ourselves.
+	if [[ "$?" != "0" ]]; then
+		trap - DEBUG
+		return
+	fi
     # Skip special commands
-    if [[ "${BASH_COMMAND}" == trap* ]] || [[ "${BASH_COMMAND}" == false ]]; then
+    if [[ "${BASH_COMMAND}" == trap* ]] || [[ "${BASH_COMMAND}" == false ]] || [[ "${BASH_COMMAND}" == *command-not-found* ]]; then
         return
     fi
 	if [[ "${BB_PRINT_COMMANDS}" == "true" ]]; then
@@ -15,7 +23,7 @@ save_history() {
 
 # Save our environment into `/workspace/metadir/env`, eliminating read-only variables
 # so that this file can be sourced upon entering a debug shell.
-save_env() {
+function save_env() {
 	set +x
 	set > /workspace/metadir/env
 	# Ignore read-only variables
@@ -30,13 +38,17 @@ if [ -f /workspace/metadir/env ]; then
 	source /workspace/metadir/env
 fi
 
+function on_error_trap() {
+	RET="$?"
+	# Disable any further traps here
+	trap - TERM EXIT
+	set +e +x
+	if [[ "${RET}" != 0 ]]; then \
+		echo "Previous command '${BASH_COMMAND}' exited with code ${RET}" >&2; \
+	fi
+	save_env
+	exit "${RET}"
+}
+
 # On any kind of exit, save our environment out to our metadir
-trap "RET=\$?; \
-	trap - DEBUG TERM ERR EXIT; \
-    set +e +x; \
-	if [[ "\$RET" != 0 ]]; then \
-    	echo Previous command \"'\${BASH_COMMAND}'\" exited with code \$RET >&2; \
-	fi; \
-    save_env; \
-    exit \$RET" \
-    TERM EXIT
+trap on_error_trap TERM EXIT
